[time]
format = '[$time](white)'
disabled = false

[username]
format = '[$user](#888888) [@](blue) '
show_always = true

[directory]
format = "$path [$read_only]($read_only_style)"
style = "white"
truncation_length = 8
truncate_to_repo = false

[directory.substitutions]

[git_branch]
format = "[ $branch](dimmed green) "

[git_status]
format = '([$ahead_behind\[$all_status \]](dimmed white))'

modified = " [$count ](red)"
untracked = " [$count ](red) "
deleted = " [$count 﫧](red) "
renamed = " [$countﭯ](red) "

staged = " [$count](dimmed red) "

conflicted = " $count [!=](yellow) "

stashed = " $count [](dimmed white) "

ahead = " $count [](dimmed white) "
behind = " $count [](dimmed white) "
diverged = " [](dimmed red) "

[package]
format = "[$symbol]($style)"
symbol = " "
display_private = true

[aws]
format = "[$symbol]($style)"
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
format = "[$symbol]($style)"
symbol = " "

[docker_context]
format = "[$symbol]($style)"
symbol = " "

[elixir]
format = "[$symbol]($style)"
symbol = " "

[elm]
format = "[$symbol]($style)"
symbol = " "

[golang]
format = "[$symbol]($style)"
symbol = " "

[hg_branch]
format = "[$symbol]($style)"
symbol = " "

[java]
format = "[$symbol]($style)"
symbol = " "

[julia]
format = "[$symbol]($style)"
symbol = " "

[memory_usage]
format = "[$symbol]($style)"
symbol = " "

[nim]
format = "[$symbol]($style)"
symbol = " "

[nix_shell]
format = "[$symbol]($style)"
symbol = " "

[nodejs]
format = "[$symbol]($style)"
symbol = " "

[php]
format = "[$symbol]($style)"
symbol = " "

[python]
format = "[$symbol]($style)"
symbol = " "

[ruby]
format = "[$symbol]($style)"
symbol = " "

[rust]
format = "[$symbol]($style)"
symbol = " "