format = """[
$time \
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch \
$git_commit\
$git_state\
$git_status \
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$lua\
$line_break\
$cmd_duration\
$jobs\
$battery\
$status\
$character](bold white)"""

[time]
format = '[ $time ](bg:#888888 fg:black)'
disabled = false

[username]
format = '[ $user @ ](bg:#888888 fg:black)'
show_always = true

[directory]
format = "$path [$read_only]($read_only_style)"
style = "white"
truncation_length = 8
truncate_to_repo = false

[directory.substitutions]

[git_branch]
format = "[ $branch](dimmed green)"

[git_status]
format = '([$ahead_behind\[$all_status \]](dimmed white))'

modified = " [$count ](red)"
modified_count = { style = "red", enabled = true }
untracked = " [$count ](red) "
untracked_count = { style = "red", enabled = true }
deleted = " [$count 﫧](red) "
deleted_count = { style = "red", enabled = true }
renamed = " [$countﭯ](red) "
renamed_count = { style = "red", enabled = true }

staged = " [$count](dimmed red) "
staged_count = { enabled = true, style = "dimmed red" }

conflicted = " $count [!=](yellow) "
conflicted_count = { enabled = true, style = "yellow" }

stashed = " $count [](dimmed white) "
stashed_count = { style = "dimmed white", enabled = true }

ahead = " $count [](dimmed white) "
behind = " $count [](dimmed white) "
show_sync_count = true
diverged = " [](dimmed red) "

[package]
format = "[$symbol]($style)"
symbol = " "
display_private = true

[aws]
format = "[$symbol]($style)"
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
format = "[$symbol]($style)"
symbol = " "

[docker]
format = "[$symbol]($style)"
symbol = " "

[elixir]
format = "[$symbol]($style)"
symbol = " "

[elm]
format = "[$symbol]($style)"
symbol = " "

[golang]
format = "[$symbol]($style)"
symbol = " "

[haskell]
format = "[$symbol]($style)"
symbol = " "

[hg_branch]
format = "[$symbol]($style)"
symbol = " "

[java]
format = "[$symbol]($style)"
symbol = " "

[julia]
format = "[$symbol]($style)"
symbol = " "

[memory_usage]
format = "[$symbol]($style)"
symbol = " "

[nim]
format = "[$symbol]($style)"
symbol = " "

[nix_shell]
format = "[$symbol]($style)"
symbol = " "

[nodejs]
format = "[$symbol]($style)"
symbol = " "

[php]
format = "[$symbol]($style)"
symbol = " "

[python]
format = "[$symbol]($style)"
symbol = " "

[ruby]
format = "[$symbol]($style)"
symbol = " "

[rust]
format = "[$symbol]($style)"
symbol = " "